import type { CarPhoto } from "@/domain/catalog";

/* GENERATED by `npm run photos:process` from photos/manifest.json — do not edit by hand.
 * Credits are required by each photo's licence; they are shown on car pages and on /credits. */

export const carPhotos: Readonly<Record<string, readonly CarPhoto[]>> = {
  "bmw-m3-g80": [
    {
      id: "main",
      mode: "cutout",
      alt: "Blue BMW M3 Competition (G80), front three-quarter view, parked on grass",
      width: 1920,
      height: 793,
      widths: [
        320,
        640,
        1280,
        1920
      ],
      focal: {
        x: 50,
        y: 50
      },
      color: "transparent",
      credit: {
        kind: "third-party",
        title: "BMW M3 (G80, 2022) (52227837026)",
        author: "Charles from Port Chester, New York",
        licenseName: "CC BY 2.0",
        licenseUrl: "https://creativecommons.org/licenses/by/2.0/",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:BMW_M3_(G80,_2022)_(52227837026).jpg",
        sourceName: "Wikimedia Commons",
        note: "Cropped, plates and faces covered, background removed."
      }
    }
  ],
  "bmw-m4-g82": [
    {
      id: "main",
      mode: "cutout",
      alt: "Dark blue BMW M4 Competition (G82), front three-quarter view",
      width: 1920,
      height: 940,
      widths: [
        320,
        640,
        1280,
        1920
      ],
      focal: {
        x: 50,
        y: 50
      },
      color: "transparent",
      credit: {
        kind: "third-party",
        title: "2021 BMW M4 Competition",
        author: "Calreyn88",
        licenseName: "CC BY 4.0",
        licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:2021_BMW_M4_Competition.jpg",
        sourceName: "Wikimedia Commons",
        note: "Cropped, plates and faces covered, background removed."
      }
    }
  ],
  "porsche-911-992": [
    {
      id: "main",
      mode: "cutout",
      alt: "Blue Porsche 911 Carrera S (992), front three-quarter view",
      width: 1920,
      height: 963,
      widths: [
        320,
        640,
        1280,
        1920
      ],
      focal: {
        x: 50,
        y: 55
      },
      color: "transparent",
      credit: {
        kind: "third-party",
        title: "2025 Porsche 911 Carrera S",
        author: "TTTNIS",
        licenseName: "CC0",
        licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:2025_Porsche_911_Carrera_S.jpg",
        sourceName: "Wikimedia Commons",
        note: "Cropped, plates and faces covered, background removed."
      }
    }
  ],
  "porsche-911-gt3-rs-992": [
    {
      id: "main",
      mode: "cutout",
      alt: "Red Porsche 911 GT3 RS (992) with white stripes on a display turntable",
      width: 1920,
      height: 810,
      widths: [
        320,
        640,
        1280,
        1920
      ],
      focal: {
        x: 55,
        y: 55
      },
      color: "transparent",
      credit: {
        kind: "third-party",
        title: "2024 911 GT3 RS (53536704621)",
        author: "Mustang Joe",
        licenseName: "CC0",
        licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:2024_911_GT3_RS_(53536704621).jpg",
        sourceName: "Wikimedia Commons",
        note: "Cropped, plates and faces covered, background removed."
      }
    }
  ],
  "audi-rs6-c8": [
    {
      id: "main",
      mode: "cutout",
      alt: "Dark blue Audi RS 6 Avant (C8) parked on grass under autumn trees",
      width: 1920,
      height: 981,
      widths: [
        320,
        640,
        1280,
        1920
      ],
      focal: {
        x: 49,
        y: 53
      },
      color: "transparent",
      credit: {
        kind: "third-party",
        title: "Audi RS 6 Avant (2021) (52451226524)",
        author: "Charles from Port Chester, New York",
        licenseName: "CC BY 2.0",
        licenseUrl: "https://creativecommons.org/licenses/by/2.0/",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:Audi_RS_6_Avant_(2021)_(52451226524).jpg",
        sourceName: "Wikimedia Commons",
        note: "Cropped, plates and faces covered, background removed."
      }
    }
  ],
  "audi-r8-4s": [
    {
      id: "main",
      mode: "cutout",
      alt: "White Audi R8 V10 Performance (Typ 4S), front three-quarter view in a showroom",
      width: 1920,
      height: 1218,
      widths: [
        320,
        640,
        1280,
        1920
      ],
      focal: {
        x: 46,
        y: 48
      },
      color: "transparent",
      credit: {
        kind: "third-party",
        title: "2023 Audi R8 Coupe V10 Performance RWD at Audi Manchester 01",
        author: "MoCars",
        licenseName: "CC0",
        licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:2023_Audi_R8_Coupe_V10_Performance_RWD_at_Audi_Manchester_01.jpg",
        sourceName: "Wikimedia Commons",
        note: "Cropped, plates and faces covered, background removed."
      }
    }
  ],
  "mercedes-amg-gt-c190": [
    {
      id: "main",
      mode: "cutout",
      alt: "Yellow Mercedes-AMG GT S (C190), front three-quarter view on a display floor",
      width: 1920,
      height: 1352,
      widths: [
        320,
        640,
        1280,
        1920
      ],
      focal: {
        x: 50,
        y: 49
      },
      color: "transparent",
      credit: {
        kind: "third-party",
        title: "Mercedes-AMG GT S (C190) front",
        author: "Tokumeigakarinoaoshima",
        licenseName: "CC0",
        licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:Mercedes-AMG_GT_S_(C190)_front.JPG",
        sourceName: "Wikimedia Commons",
        note: "Cropped, plates and faces covered, background removed."
      }
    }
  ],
  "nissan-gt-r-r35": [
    {
      id: "main",
      mode: "cutout",
      alt: "Grey-blue Nissan GT-R NISMO (R35) with carbon bonnet and red trim, on a black display stage",
      width: 1920,
      height: 1147,
      widths: [
        320,
        640,
        1280,
        1920
      ],
      focal: {
        x: 53,
        y: 55
      },
      color: "transparent",
      credit: {
        kind: "third-party",
        title: "Nissan 4BA-R35 GT-R NISMO Special edition (Ent No.30302) (24021013210)",
        author: "先従隗始",
        licenseName: "CC0",
        licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:Nissan_4BA-R35_GT-R_NISMO_Special_edition_(Ent_No.30302)_(24021013210).jpg",
        sourceName: "Wikimedia Commons",
        note: "Cropped, plates and faces covered, background removed."
      }
    }
  ],
  "lamborghini-huracan-lp610": [
    {
      id: "main",
      mode: "cutout",
      alt: "Lime green Lamborghini Huracán LP 610-4, front three-quarter view on a black show carpet",
      width: 1920,
      height: 1071,
      widths: [
        320,
        640,
        1280,
        1920
      ],
      focal: {
        x: 49,
        y: 56
      },
      color: "transparent",
      credit: {
        kind: "third-party",
        title: "Lamborghini Huracan LP610-4 (16280529768)",
        author: "Jacob Frey 4A",
        licenseName: "CC BY 2.0",
        licenseUrl: "https://creativecommons.org/licenses/by/2.0/",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:Lamborghini_Huracan_LP610-4_(16280529768).jpg",
        sourceName: "Wikimedia Commons",
        note: "Cropped, plates and faces covered, background removed."
      }
    }
  ],
  "ford-mustang-gt-s550": [
    {
      id: "main",
      mode: "cutout",
      alt: "Black Ford Mustang GT (S550) with red brake calipers, parked on grass",
      width: 1920,
      height: 904,
      widths: [
        320,
        640,
        1280,
        1920
      ],
      focal: {
        x: 50,
        y: 48
      },
      color: "transparent",
      credit: {
        kind: "third-party",
        title: "Ford Mustang GT (41657274580)",
        author: "FotoSleuth",
        licenseName: "CC BY 2.0",
        licenseUrl: "https://creativecommons.org/licenses/by/2.0/",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:Ford_Mustang_GT_(41657274580).jpg",
        sourceName: "Wikimedia Commons",
        note: "Cropped, plates and faces covered, background removed."
      }
    }
  ]
};
